apiVersion: 1

datasources:
  - name: PostgreSQL
    type: grafana-postgresql-datasource
    uid: backend_support_pg
    access: proxy
    url: postgres:5432
    database: vacancy_mirror
    user: app
    secureJsonData:
      password: ${DB_PASSWORD}
    jsonData:
      sslmode: disable
      postgresVersion: 1600
      timescaledb: false
    isDefault: true
    editable: false

