[supervisord]
nodaemon=true
logfile=/dev/null
logfile_maxbytes=0
pidfile=/tmp/supervisord.pid
user=root

[program:cron]
command=/usr/sbin/cron -f
autorestart=true
stdout_logfile=/dev/fd/1
stdout_logfile_maxbytes=0
stderr_logfile=/dev/fd/2
stderr_logfile_maxbytes=0

[program:scraper-api]
command=uvicorn scraper_api.main:app --host 0.0.0.0 --port 8000 --workers 1
directory=/app
autorestart=true
environment=PYTHONUNBUFFERED="1"
stdout_logfile=/dev/fd/1
stdout_logfile_maxbytes=0
stderr_logfile=/dev/fd/2
stderr_logfile_maxbytes=0
